TOKEN: fa1f534b52a92e51c5c4b9e32c7f1da5
API_KEY_INSIDER_TRADING: https://financialmodelingprep.com/api/v4/insider-trading?transactionType=P-Purchase&page=0&apikey=
API_KEY_INSIDER_TICK: https://financialmodelingprep.com/api/v4/insider-trading?symbol=
API_KEY_RATIOS: https://financialmodelingprep.com/api/v3/ratios/
API_KEY_METRICS: https://financialmodelingprep.com/api/v3/key-metrics/
